>**기출문제 제8회**
>>**03 작업형 제3유형**

# 문제 1. 
- 어느 회사에서 직원들의 업무 효율성을 높이기 위한 새로운 소프트웨어를 도입하였다.
- 도입 전과 도입 후의 업무 처리 시간을 각각 측정하여 새로운 소프트웨어의 효과를 검증하고자 한다.

In [16]:
import pandas as pd
data = pd.read_csv('8_3_1.csv')
data.head(), data.shape

(      before      after
 0  10.646079  10.541545
 1   8.600236   7.213333
 2   9.468107   8.978912
 3  11.361340  11.541972
 4  10.801337   9.829519,
 (50, 2))

- 도입 전과 도입 후의 업무처리 시간의 평균과 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)

In [ ]:
# 코드

도입 전 업무 처리 시간 평균: 8.21
도입 전 업무 처리 시간 표준편차: 1.71
도입 후 업무 처리 시간 평균: 7.23
도입 후 업무 처리 시간 표준편차: 1.96

- 도입 전후의 업무처리 시간 차이가 유의미한지 부호 순위 검정을 실시하고, 검정통계량을 계산하시오. (p-value 소수점 둘째 자리까지 반올림
- HINT : 윌콕슨 부호 순위 검정 (비모수 검정 메서드도 익힐 필요 있음, 빅데이터 분석기사 시험)

In [18]:
# 코드

검정통계량: 72.0

- p-value를 바탕으로 `유의수준 5%`에서 귀무가설의 기각/채택 여부를 결정하시오.
- p-value는 소수점 셋째 자리까지 반올림

In [19]:
# 코드

기각

# 문제 2. 
- 어느 회사에서 직원들의 업무 효율성을 높이기 위한 새로운 소프트웨어를 도입하였다.
- 도입 전과 도입 후의 업무 처리 시간을 각각 측정하여 새로운 소프트웨어의 효과를 검증하고자 한다.

In [20]:
import pandas as pd
train_data = pd.read_csv('8_3_2_train.csv')
test_data = pd.read_csv('8_3_2_test.csv')

train_data.head(1)

   productivity      hours  age  experience
0    201.358765  49.753877   34          24

In [21]:
test_data.head(1)

   productivity      hours  age  experience
0    160.320183  40.228793   35           8

- 훈련 데이터를 기준으로 생산성 점수(productivity)를 종속변수로 하고 근무 시간, 연령, 그리고 경력을 독립변수로 하는 다중회귀 분석을 수행한 후, 회귀계수가 가장 높은 변수를 구하시오.

In [22]:
# 코드

                            OLS Regression Results
==============================================================================
Dep. Variable:           productivity   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     69.03
Date:                Sat, 17 May 2025   Prob (F-statistic):           1.20e-21
Time:                        20:42:09   Log-Likelihood:                -297.10
No. Observations:                  80   AIC:                             602.2
Df Residuals:                      76   BIC:                             611.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         67.2310     11.097      6.059      0.000      45.130      89.332
hours          1.6182      0.226      7.169      0.000       1.169       2.068
age            0.4311      0.110      3.904      0.000       0.211       0.651
experience     1.5323      0.124     12.380      0.000       1.286       1.779
==============================================================================
Omnibus:                        3.122   Durbin-Watson:                   1.692
Prob(Omnibus):                  0.210   Jarque-Bera (JB):                2.381
Skew:                           0.380   Prob(JB):                        0.304
Kurtosis:                       3.372   Cond. No.                         611.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
# 코드

회귀계수가 가장 큰 변수: hours

- 유의수준 5% 하에서 각 독립변수가 생산성에 미치는 영향이 통계적으로 유의미한지 판단하고, 유의미한 변수 개수를 구하시오.
- p-value는 소수점 넷째 자리까지 반올림

In [24]:
# 코드

유의미한 변수 개수: 3
hours         0.0000
age           0.0002
experience    0.0000
dtype: float64

- (옵션) 테스트 데이터로 모델의 성능을 평가하시오. \
-

In [25]:
# 코드

테스트 데이터 Rsquared: 0.804