>**기출문제 제5회**
>>**01 작업형 제1유형**

## 옵션 설정

In [6]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None) # 모든 칼럼이 출력되게 조절

## 문제 1. 
- 다음 데이터에서 conventional 컬럼의 특수문자를 제거하고, IQR(3분위수-1분위수)를 구하시오. 
- 소수점 첫째 자리에서 반올림

In [9]:
# 코드
data = pd.read_csv('5_1_1.csv')
data1 = data.copy()

In [10]:
# 영어, 숫자, 한국어를 제외한 모든 문자 제거 
# 정규표현식
data1.loc[:,'conventional'] = data1.loc[:,'conventional'].str.replace(r'[^a-zA-Z0-9가-힣]','',regex=True)
data1
# 코드

,minority,crime,poverty,language,highschool,housing,city,conventional,undercount,date
0,26.1,49,18.9,0.2,43.5,7.6,state,,-0.04,2023-01-01
1,5.7,62,10.7,1.7,17.5,23.6,state,,3.35,2023-01-02
2,18.9,81,13.2,3.2,27.6,8.1,state,,2.48,2023-01-03
3,16.9,38,19.0,0.2,44.5,7.0,state,,-0.74,2023-01-04
4,24.3,73,10.4,5.0,26.0,11.8,state,4,3.60,2023-01-05
...,...,...,...,...,...,...,...,...,...,...
61,41.3,60,20.6,2.2,45.7,21.7,city,0,6.41,2023-03-03
62,46.7,143,21.8,0.5,51.8,40.9,city,0,3.60,2023-03-04
63,23.6,81,12.4,4.2,21.1,11.2,city,0,0.47,2023-03-05
64,24.8,107,13.7,9.2,26.0,20.3,city,0,5.18,2023-03-06
65,72.6,102,18.6,1.1,32.9,21.0,city,0,5.93,2023-03-07

In [14]:
# 코드
# 공백 처리, NaN으로 처리 => 데이터 타입을 변경, float, int
data1.loc[:,'conventional'] = data1.loc[:,'conventional'].replace('',np.nan)
data1.loc[:,'conventional'] = data1.loc[:,'conventional'].astype(float)

# IQR계산
# quantile(), IQR구하기

10.580645161290322 22.906472982433943

## 문제 2. 
- 위 데이터에서 흑인 또는 히스패닉 비율(minority) / 빈곤율(poverty) > 2이며, 도시 유형(city)이 state인 도시의 범죄율(crime) 평균을 구하시오. 
- 소수점 첫째 자리에서 반올림

In [8]:
# 코드
# minority / poverty > 2 & city : state

round(result_df.loc[:,'cirme'].mean(), 1)

범죄율 평균: 61.0

## 문제 3. 
- 다음 데이터에서 2016년 9월 이후, 온도(actual)의 평균을 구하시오. (소수점 첫째 자리에서 반올림)

In [9]:
# 코드 
data3 = pd.read_csv('5_1_2.csv')
data3.head(1)

   year  month  day week  temp_2  temp_1  average  actual  friend
0  2016      1    1  Fri      45      45     45.6      45      29

In [10]:
# 코드
# 2016년 9월 이후 데이터 필터링
filtered_data = data3.loc[(data3.loc[:, 'year'] == 2016) & (data3.loc[:, 'month'] >= 9)]

# 필터링된 데이터의 actual 평균 계산 및 반올림
actual_mean = round(filtered_data.loc[:, 'actual'].mean(), 0)

print(f'2016년 9월 이후 온도 평균: {actual_mean}')

2016년 9월 이후 온도 평균: 58.0

In [16]:
# 코드
data3['date'] = pd.to_datetime(dict(year=data3['year'], month=data3['month'], day=data3['day']))

# date를 인덱스로 설정
data4 = data3.copy()
data4.set_index('date', inplace=True)

# 2016-09-01 이후 데이터 필터링 및 평균 계산
data4.loc['2016-09-01':, 'actual'].mean()

2016년 9월 이후 온도 평균: 58.0